www/aivs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template, redirect_to
from django.contrib import admin

from aivs import views

'''
This module performs the routing of URLs to the appropriate views and serves as the root
URL configuration file.  It routes by inclusion to the registration and admin URLs.
'''

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', direct_to_template, { 'template': 'home.html' }, name='home'),
    url(r'^home/$', redirect_to, { 'url': '/' }),
    url(r'^about/$', direct_to_template, { 'template': 'about.html' }, name='about'),
    url(r'^contact/$', views.contact, name='contact'),

    # these urls use the same view but control template with passed arguments
    url(r'^profile/$', views.profile_and_reports, { 'template': 'profile.html' }, name='profile'),
    url(r'^reports/$', views.profile_and_reports, { 'template': 'profile_table.html' }, name='reports'),

    # scan workflow urls
    url(r'^scan/$', views.request_scan, name='scan'),
    url(r'^scan_running/$', views.slideshow, name='slideshow'),
    url(r'^report/(?P<id>\d+)/$', views.scan_report, name='scan_report'),

    # included apps
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('registration_backend.urls')),  # registration must be before auth to override login
    url(r'', include('django.contrib.auth.urls')),
)

www/aivs/forms.py
from django import forms
from bootstrap.forms import BootstrapForm, Fieldset


class ScanRequestForm(BootstrapForm):
    '''
    A mini-form to initiate the scanner workflow.
    '''
    class Meta:
        layout = (
            Fieldset("Request a Scan",
                     "accepts_terms"),
            )

    accepts_terms = forms.BooleanField(label='I accept the Terms and Conditions',
                                       help_text = 'See the Terms and Conditions on this page.',
                                       error_messages={'required': 'You must accept the Terms and Conditions'})


class ContactForm(BootstrapForm):
    '''
    A form to initiate the contact-us workflow.
    '''
    class Meta:
        layout = (
            Fieldset('ContactUs',
                     'email_address',
                     'email_verify',
                     'message'),
            )

    email_address = forms.EmailField( label = 'Email Address',
                                      initial = 'Enter your email address',
                                      widget = forms.TextInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                      help_text = 'Your valid email address, up to 200 characters.',
                                      error_messages = { 'required': 'You must supply an email address.',
                                                         'invalid': 'That does not appear to be a valid email address.',
                                                         'max_length': 'A maximum of 200 characters, please.'},
                                      max_length=200)

    email_verify = forms.EmailField( label = 'Verify Email',
                                      initial = 'Enter your email address',
                                      widget = forms.TextInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                      help_text = 'Your valid email address, up to 200 characters.',
                                      error_messages = { 'required': 'You must confirm your email address.',
                                                         'invalid': 'That does not appear to be a valid email address.',
                                                         'max_length': 'A maximum of 200 characters, please.'},
                                      max_length=200)

    message = forms.CharField( label = 'Message',
                                  initial = 'Enter a message here.',
                                  widget = forms.Textarea(attrs = {'rows' : 6, 'class' : 'span4 input-large'}),
                                  help_text = 'Your message here.',
                                  error_messages = { 'required': 'You must supply a message.',
                                                     'max_length': 'A maximum of 10000 characters, please.'},
                               max_length=10000)

    def clean_email_address(self):
        '''
        Verifies that the email addresses provided match.
        complexity.
        '''
        candidate = self.data['email_address']
        if candidate != self.data['email_verify']:
            raise forms.ValidationError('These email addresses don\'t match.  Please try again.')
        return candidate

www/aivs/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.template import RequestContext

import re
import simplejson

from aivs.forms import ContactForm, ScanRequestForm
from scanner import tasks
from scanner.models import *
'''
This module contains the main logic of the web application.  Although the module is called views
in the Django convention, this module takes the role of Controller in the classic MVC pattern.
'''

@login_required(login_url='/login/')
def request_scan(request):
    ip = get_client_ip(request)
    if not ip:
        return HttpResponseForbidden # invalid client IP address sent

    if request.method == 'POST':
        # we bind a form to the POST data
        form = ScanRequestForm(request.POST)
        if form.is_valid():
            # form.cleaned_data now contains only valid data
            user = request.user
            tasks.run_scan.delay(user, ip)
            return HttpResponseRedirect(reverse('slideshow'))
    else:
        # form has not been submitted, so prepare an unbound form
        form = ScanRequestForm()
    return render_to_response('scan.html', {'form': form, 'ip': ip},
                              context_instance=RequestContext(request))


@login_required(login_url='/login/')
def profile_and_reports(request, template='profile.html'):
    '''
    Gets the user profile and serves the Ajax call to get the table of scans.
    '''
    scans = list(Scan.objects.filter(user_id=request.user).order_by('-start_time'))
    for scan in scans:
        try:
            host = Host.objects.get(scan=scan.pk)
            scan.ip = host.ip4
            scan.hostname = host.hostname
        except Host.DoesNotExist:
            scan.hostname = 'pending...'
    return render_to_response(template, {'scans': scans},
                              context_instance=RequestContext(request))

@login_required(login_url='/login/')
def slideshow(request):
    return render_to_response('slideshow.html',
                              context_instance=RequestContext(request))


@login_required(login_url='/login/')
def scan_report(request, id):
    '''
    Generates the in-browser report.
    '''
    user = request.user
    try:
        report = Scan.objects.get(pk=id, user_id=user.id)
        report_contents = get_report_contents(report)
        return render_to_response('report.html',
                                  context_instance=RequestContext(request, report_contents))
    except Scan.DoesNotExist:
        return HttpResponseRedirect(reverse('profile')) # TODO: do some kind of proper error handling here

def get_report_contents(report):
    '''
    Helper function to query a scan and gets its related objects to build a dict suitable to construct a
    Context or RequestContext from for use in a template.  Get used by scan_report view and by
    the scanner task that sends email reports.
    '''
    host = Host.objects.get(scan=report.pk)
    ports = FoundPort.objects.select_related('KnownPort').filter(host=host.pk)
    vulns = KnownVulnerability.objects.filter(foundvulnerability__host=host.pk)
    try:
        OS = host.os
    except:
        OS = MockModel()
        OS.name = 'No OS information detected.'
    return { 'report':report, 'host': host, 'ports': ports, 'vulns': vulns, 'OS': OS }


def contact(request):
    if request.method == 'POST':
        # bind a form to the POST data
        form = ContactForm(request.POST)
        if form.is_valid():
            # form.cleaned_data now contains only valid data
            user_email = form.cleaned_data['email_address']
            message = form.cleaned_data['message']
            tasks.send_admin_email(user_email, message)
            return HttpResponseRedirect('/')
    else:
        # the form has not been submitted, so prepare an unbound form
        form = ContactForm()
    return render_to_response('contact.html', {'form': form},
                              context_instance=RequestContext(request))


ip_regex_pattern = re.compile(r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$')

def get_client_ip(request):
    '''
    Gets the client IP address from the request header set by the Nginx proxy, and performs some
    simple validation.  If the check fails in a debug environment (ex. local development without
    Nginx proxy), fill in the local IP.
    In a production environment, we might not want to use this header by itself, as load balancers
    might show up as the IP.
    '''
    ip = request.META.get('HTTP_X_REAL_IP', None)
    if ip and ip_regex_pattern.match(ip):
        return ip
    elif settings.DEBUG:
        return 'localhost'
    else:
        return None

www/aivs/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="hero-unit">
  <h1>Why AIVScan?</h1>
</div>

<p>Today, some of our most valuable assets are in the form of electronic information. As such, we must take measures to protect our data and ensure that it doesn’t fall into the wrong hands. External threats, whether hackers or viruses, are a concern that is difficult to evaluate and assess. AIVScan is designed to give individuals and organizations the ability to quickly and efficiently assess their external footprint.</p>

<p>AIVScan is a web-based security evaluation application. Its primary goal is to efficiently and accurately assess the security of a computer. AIVScan will be designed for all types of users, home or business, regardless of technical sophistication. Our service is an automatic security scan that determines Internet-accessible services, their vendor and version, and any known vulnerabilities that can endanger the user’s computer and stored information. The product will automatically obtain much of the information necessary to conduct the security scan, including IP address, operating system, and others.</p>

<p>The scan will be conducted with increased depth. The first step will be to identify the services running on the computer. The second step will dig deeper and determine the vendor and version of each. The final step will attempt to ascertain if any of the services expose the user to risk via known software vulnerabilities.</p>

<p>The main output of AIVScan will be a security report. Users will receive this report through an email address that they must register on our website. The document will be presented in a very user friendly and non-technical format. Clients will be offered a summary of the results, detailed findings, and our suggestions for remediation actions. Each vulnerability discovered will be rated on a scale from Critical to Low. The secondary output of AIVScan will be in the form of educational slide shows that will be displayed while a security scan is in progress. These presentations will be designed to increase the users’ awareness of security topics such as password strength, avoiding phishing attacks, and others.</p>

<p>The primary goal of AIVScan is to improve the overall security profile of our users’ computers. If our clients follow through with our suggestions for improvement, they will improve their computer’s security and help protect their sensitive information.</p>
{% endblock %}

www/aivs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
{% include "head_include.html" %}
{% block head %}{% endblock %}
</head>

<body>
{% include "nav_include.html" %}

<div class="container">
   {% include "user_sidebar.html" %}
   <div class="span8">
   {% block content %}{% endblock %}
   </div>
</div>

{% include "footer_and_scripts.html" %}
{% block scripts %}{% endblock %}

</body>
</html>

www/aivs/templates/base_modal.html
{% if not request.is_ajax %}
<!DOCTYPE html>
<html lang="en">
<head>
{% include "head_include.html" %}
{% block head %}{% endblock %}
</head>

<body>
{% include "nav_include.html" %}

<div class="container">
  <div class="row">
     <div class="span2"
       <p><img src="{{ STATIC_URL }}img/aivscan_logo.png" height="150px" width="175px" /></p>
     </div><!-- span2 -->
     <div class="span8">

<div class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto; z-index: 1; max-width: 100%;">
{% endif %} <!-- /no ajax -->

{% block modalform %}{% endblock %}

{% if not request.is_ajax %}
</div><!-- /modal -->

 </div><!-- span8 -->
</div> <!-- /container -->

{% include "footer_and_scripts.html" %}
{% block scripts %}{% endblock %}

  </body>
</html>
{% endif %} <!-- /no ajax -->

www/aivs/templates/contact.html
{% extends "base_modal.html" %}
{% block modalform %}
<form id="modal-form" method="post" action="{% url contact %}" class="well form-vertical">

<div class="modal-header">
  <h2>Contact Pwn Stars</h2>
</div>

<div class="modal-body">
  <p>Fill out and submit this handy form to contact us!</p>
  <hr>
{% csrf_token %}
<span style="color:red">{{ form.non_field_errors }}</span>
<div class="control-group">
  <span style="color:red">{{ form.email_address.errors }}</span>
  <label for="id_email_address" class="regfields">Email Address</label>
  <div class="controls">{{ form.email_address }}</div>
</div>
<div class="control-group">
  <span style="color:red">{{ form.email_verify.errors }}</span>
  <label for="id_email_address_verify" class="regfields">Confirm Email</label>
  <div class="controls">{{ form.email_verify }}</div>
</div>
<div class="control-group">
  <span style="color:red">{{ form.message.errors }}</span>
  <label for="id_message" class="regfields">Message</label>
  <div class="controls">{{ form.message }}</div>
</div>
<div  class="form-actions">
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="#" class="btn" data-dismiss="modal">Cancel</a>
</div>
</div> <!-- end modal body -->

</form>
{% endblock %}

www/aivs/templates/footer_and_scripts.html
<footer>
    <p>&copy; Pwn Stars {% now "Y" %}</p>
</footer>

<div class="modal hide" id="navModal"></div>

<!-- Placed at the end of the document so the pages load faster -->
<script src="{{ STATIC_URL }}js/jquery.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-transition.js"></script>
<!--    <script src="{{ STATIC_URL }}js/bootstrap-alert.js"></script>-->
<script src="{{ STATIC_URL }}js/bootstrap-modal.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
<!--    <script src="{{ STATIC_URL }}js/bootstrap-scrollspy.js"></script>-->
<!--    <script src="{{ STATIC_URL }}js/bootstrap-tab.js"></script>-->
<!--    <script src="{{ STATIC_URL }}js/bootstrap-tooltip.js"></script>-->
<!--    <script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>-->
<!--    <script src="{{ STATIC_URL }}js/bootstrap-button.js"></script>-->
<!--    <script src="{{ STATIC_URL }}js/bootstrap-collapse.js"></script>-->
<script src="{{ STATIC_URL }}js/bootstrap-carousel.js"></script>
<!--    <script src="{{ STATIC_URL }}js/bootstrap-typeahead.js"></script>-->
<script>
var current_page = "#nav-" + location.pathname.slice(1)
$(current_page).addClass("active");

$("label.regfields").addClass("control-label");

 function clearField(form) {
   $(form).find("input.input-large, textarea").each(function() {
       this.defaultValue = this.value;
       $(this).click(function() {
          if(this.value == this.defaultValue) {
              $(this).val("");
          }
          return false;
       });
       $(this).blur(function() {
           if(this.value == ""){
              $(this).val(this.defaultValue);
           }
       });
    });
}

$(".nav-to-modal").live("click", (function(x) {
    x.preventDefault(); // stops navigation on click
    var url = $(this).data("form");
    $("#navModal").load(url, function() {
        $(this).modal('show');
        clearField("#modal-form");
    });
    return false;
}))

</script>

www/aivs/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
<!-- note this page does not extend base.html -->
{% include "head_include.html" %}
<style>
.mainlogo {
   margin-bottom: 2em;
   margin-top: 1em;
   margin-right: 2em;
   float: left;
}
</style>
</head>

<body>
{% include "nav_include.html" %}

<div class="container">

  <!--Borrowed this portion from the hero.html bootstrap template -->
    <div class="hero-unit" style="width:980px;">
       <p><img src="{{ STATIC_URL }}img/aivscan_logo.png" height="150px" width="175px" class="mainlogo"/></p>
      <h1>Welcome to AIVScan!</h1>
      <p>AIVScan is a web-based security evaluation application. Click the pretty blue button to get started! </p>
      <p>
      {% if user.is_authenticated %}
      <a class="btn btn-primary btn-large" href="{% url scan %}">Get Started &raquo;</a>
      {% else %}
      <a class="btn btn-primary btn-large nav-to-modal" href="{% url registration_register %}" data-form="{% url registration_register %}">Get Started &raquo;</a>
      {% endif %}
      </p>
     </div>

  <div class="row">

     <div class="span8">
      <h2>What is AIVScan?</h2>
<p>AIVScan is a web-based security evaluation application. Its primary goal is to efficiently and accurately assess the security of a computer. AIVScan is designed for all types of users, home or business, regardless of technical sophistication. Our service is an automatic security scan that determines Internet-accessible services, their vendor and version, and any known vulnerabilities that can endanger the user’s computer and stored information. The product will automatically obtain much of the information necessary to conduct the security scan, including IP address, operating system, and others.</p>
 <p>The primary goal of AIVScan is to improve the overall security profile of our users’ computers. If our clients follow through with our suggestions for improvement, they will improve their computer’s security and help protect their sensitive information.</p>

       {% if user.is_authenticated %}
       <p>Click <a href="{% url scan %}">here</a> to get your next scan started.<p>
       {% else %}
       <p>Click <a href="{% url registration_register %}">here</a> to learn more</p>
       {% endif %}
        </div><!-- span 8 -->
      </div><!-- row -->
</div> <!-- /container -->

{% include "footer_and_scripts.html" %}

  </body>
</html>

www/aivs/templates/nav_include.html
   <!-- Begin the navbar
    ===================================== -->
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">

          <a class="brand" href="{% url home %}">AIVScan</a>
          <div class="nav pull-right"><!-- user dropdown menu -->
            {% if user.is_authenticated %}
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i>
            {{ user.first_name }} {{ user.last_name }}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url profile %}">Profile</a></li>
              <li class="divider"></li>
              {% if user.is_staff %}
              <li><a href="{% url admin:index %}">Login to Admin</a></li>
              {% endif %}
              <li><a href="{% url logout %}">Sign Out</a></li>
            </ul>
          {% else %}
            <ul class="nav">
              <li>
              <a href="{% url auth_login %}" class="nav-to-modal"
              data-form="{% url auth_login %}">
              Login
              </a></li>
              <li>
              <a href="{% url registration_register %}" class="nav-to-modal"
              data-form="{% url registration_register %}">
              Register
              </a></li>
            </ul>
            {% endif %}
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="{% url about %}">About</a></li>
              <li><a href="{% url contact %}" class="nav-to-modal" data-form="{% url contact %}">
              Contact
              </a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div><!-- End navbar -->

    <noscript>
    <div class="noscript"><strong>Seriously, no Javascript?  It's 2012, man.</strong></div>
    </noscript>

www/aivs/templates/profile.html
{% extends "base.html" %}
{% block content %}

     <div class="hero-unit">
       <h1>{{ user.first_name }} {{ user.last_name }}</h1>
       <p>Welcome back to AIVScan! What would you like to do?</p>
       <p><a class="btn btn-primary btn-large" href="{% url scan %}">
       Start a new scan &raquo;</a></p>
     </div>

     <h2>Previous Scans</h2>
     <table class="table table-striped">
       <thead><tr><th>Date</th><th>Host</th></tr></thead>
       <tbody id="scan_table">
     </tbody>
     </table>

<div style="text-align:right">
  <a href="{% url slideshow %}">I want to see the slideshow again!</a>
</div>
{% endblock %}
{% block scripts %}
<script>
$("#scan_table").load("{% url reports %}", function() {
  return false;
});
window.setInterval( function() {
    $("#scan_table").load("{% url reports %}");
    return false;
}, 10000);
</script>
{% endblock %}

www/aivs/templates/profile_table.html
{% for scan in scans %}
<tr>
  <td class="span3">
    <a href="{% url scan_report scan.pk %}">{{ scan.end_time|date:"Y M d" }}</a>
  </td>
  <td>{{scan.ip}} {{scan.hostname}}</td>
</tr>
{% endfor %}

www/aivs/templates/report.html
{% extends "base.html" %}

{% block content %}

     <div class="hero-unit">
       <h1>Scan Complete!</h1>
     </div>
     <h2>Here's what we found...</h2>
<hr />
<!-- Begin Report
     ============ -->

<h3>Host Information</h3>
<table class="table table-striped">
	  <tr><td>Start time:</td><td>{{ report.start_time }}</td></tr>
      <tr><td>End time:</td><td>{{ report.end_time }}</td></tr>
	  <tr><td>IP address:</td><td>{{ host.ip4 }}</td></tr>
</table>

<h3>Threat Report</h3>
<table class="table table-striped">
	<thead>
	  <tr>
        <th>Threat</th>
	    <th>Risk Level</th>
        <th>ID</th>
        <th>Description</th>
        <th>Remediation</th>
          </tr>
        </thead>
<tbody>
{% for vuln in vulns %}
<tr>
  <td>{{ vuln.script_id }}</td>
  <td class="span1">
    {% if vuln.risk_level == 3 %}
    <span style="font-weight:bold;color:crimson;">Critical</span>
    {% endif %}
    {% if vuln.risk_level == 2 %}
    <span style="font-weight:bold;color:orange;">High</span>
    {% endif %}
    {% if vuln.risk_level == 1 %}
    <span style="color:orange;">Medium</span>
    {% endif %}
  </td>
  <td class="span1">{{ vuln.public_id }}</td>
  <td>{{ vuln.description }}</td>
  <td>{{ vuln.mitigation }}</td>
</tr>
{% endfor %}
</tbody>
</table>

<hr />

<h3>Port Vulnerabilities</h3>
<table class="table table-striped table-condensed">
	<thead>
          <tr>
            <th>Port</th>
            <th>Risk Level</th>
            <th>Status</th>
            <th>Description</th>
            <th>Feedback</th>
          </tr>
        </thead>
<tbody>
{% for port in ports %}
<tr>
  <td class="span2">{{ port.known_port.protocol }} / {{ port.known_port.port_number }}</td>
  <td>
    {% if port.known_port.risk_level == 3 %}
    <span style="font-weight:bold;color:crimson;">Critical</span>
    {% endif %}
    {% if port.known_port.risk_level == 2 %}
    <span style="font-weight:bold;color:orange;">High</span>
    {% endif %}
    {% if port.known_port.risk_level == 1 %}
    <span style="color:orange;">Medium</span>
    {% endif %}
  </td>
  <td class="span2">{{ port.state }}</td>
  <td>
    {% if port.known_port.description %}
    {{ port.known_port.description }}
    {% else %}
        {% if port.product %} {{ port.product }} {{ product.version }}
        {% else %}
        {{ port.service_name }}
        {% endif %}
    {% endif %}
  </td>
  <td>{{ port.known_port.mitigation }}</td>
</tr>
{% endfor %}

</tbody>
</table>

       </div><!-- span8 -->
{% endblock %}

www/aivs/templates/report_email.html
<!DOCTYPE html>
<html>

<!-- Apparently email clients don't like external style sheets or JavaScript
     So it's all embedded and inline styles in here. May God forgive me. -->
<head>
<title>Email Report</title>
<style type="text/css">
body {
    background-color:#ffffff;
    font-family:Arial, Helvetica, sans-serif;
    color:black;
}
.bubble {
    background-color:#eeeeee;
    width:600px;
    padding:10px;
    margin-bottom:30px;
    -webkit-border-radius:6px;
    -moz-border-radius:6px;
    border-radius:6px;
}
table {
    max-width:100%;
    background-color:transparent;
    border-collapse:collapse;
    border-spacing:0;
}
#output {
    width:600px;
    border-collapse:collapse;
    background-color:#ffffff;
}
#output td, #output th {
    border:1px solid black;
    padding:3px,3px,3px,3px;
    background-color:#ffffff;
}
#output th {
    font-size:1em;
    text-align:justify;
    padding-top:3px;
    padding-bottom:3px;
    padding-left:3px;
    background-color:#025036;
    color:#ffffff;
}
#output tr, #output td {
    background-color:#ffffff;
    padding-top:3px;
    padding-bottom:3px;
    padding-left:3px;
    padding-right:3px;
}
#output td {
    font-size:12px;
    text-align:left;
    border:solid 1px black;
}
</style>
</head>
<body>

<!-- Table wrapper ---------------------------- -->
<table width="100%" align="center">
  <tr>
    <td>
      <table align="center"><!-- Border of Email -->
        <tr>
          <td>
            <!-- bubble1 ------------------->
            <table class="bubble">
              <tr>
                <td><!-- Logo Img -->
                  <a href="#"><img src="https://{{site_name}}/img/aivscan_logo_hero.png" alt="aivscan"></a>
                </td>
                <td>
                  <p style="font-size:30px; font-weight:bold;">Scan Complete!</p><!-- Header -->
                </td>
              </tr>
            </table><!-- /bubble1 -->

            <!-- Table for Output --------------------------->
            <table id="output">
              <caption>Results of scan for host at IP address <span style="color:red">{{ host.ip4 }}</span></caption>
              <thead>
                <tr>
                  <th>Vulnerability</th>
                  <th>Risk Level</th>
                  <th>ID</th>
                  <th>Description</th>
                  <th>Remediation</th>
                </tr>
                </thead>
              <tbody>
                {% for vuln in vulns %}
                <tr>
                  <td>{{ vuln.script_id }}</td>
                  <td>
                    {% if vuln.risk_level == 3 %}
                    <span style="font-weight:bold;color:crimson;">Critical</span>
                    {% endif %}
                    {% if vuln.risk_level == 2 %}
                    <span style="font-weight:bold;color:orange;">High</span>
                    {% endif %}
                    {% if vuln.risk_level == 1 %}
                    <span style="color:orange;">Medium</span>
                    {% endif %}
                  </td>
                  <td>{{ vuln.public_id }}</td>
                  <td>{{ vuln.description }}</td>
                  <td>{{ vuln.mitigation }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table><!-- /output table -->
<br />
<br />
            <!-- footer --------------------------------->
            <table align="center">
              <tr align="center" style="font-size:12px;">
                <td><a href="https://{{site_name}}/profile">View report in browser</a> &nbsp;|&nbsp;
                  <a href="#">Go to the site</a> &nbsp;|&nbsp;
                  <a href="http://www.ic3.gov/default.aspx">Report us to the authorities</a>
                </td>
              </tr>
            </table>
            <p align="center" style="font-size:12px;">&copy; Pwn Stars 2012</p><!-- /footer -->
          </td>
        </tr>
      </table><!-- /Border of Email -->
    </td>
  </tr>
</table><!-- /Table wrapper -->
</body>
</html>

www/aivs/templates/scan.html
{% extends "base.html" %}

{% block head %}
<style>
.help-block {
   color: #C0C0C0;
}
</style>{% endblock %}

{% block content %}
<div class="modal" style="position: relative; top: auto; left: auto; margin: 0 auto; z-index: 1; max-width: 100%;">
<div class="modal-header">
  <h3>AIVScan is ready</h3>
</div>
<div class="modal-body">
<p>You're all set! Your IP address is <code>{{ ip }}</code>. Click the blue button to start AIVScan.</p>
  <form id="scan-form" method="post" action="{% url scan %}" class="form-horizontal">
  {% csrf_token %}
<div class="control-group">
  {{ form.accepts_terms.errors }}
  <label class="checkbox">
  {{ form.accepts_terms }}
  <strong>I have read and accept AIVScan <a data-toggle="modal" href="#terms-modal">terms</a>.</strong>
  </label>
</div>
<div  class="modal-footer form-actions">
  <button class="btn"><a href="{% url home %}">Cancel</a></button>
  <button type="submit" class="btn btn-primary">Scan</button>
</div>
</form>
</div> <!-- modal body -->
</div><!-- Modal -->

<!-- terms and conditions modal -->
<div class="modal fade hide" id="terms-modal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Terms and Conditions</h3>
  <div class="modal-body">
{% include "terms_and_conditions.html" %}
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      </div>
 </div></div>
<!-- end terms and conditions modal -->

{% endblock %}
{% block scripts %}
<script type="text/javascript">
$("label.regfields").addClass("control-label");
</script>
{% endblock %}

www/aivs/templates/user_sidebar.html
<div class="span3">
<div class="well sidebar-nav">
<div class="container-fluid">
  <img src="{{ STATIC_URL }}img/aivscan_logo.png"/>
</div>
{% if request.user.is_authenticated %}
<ul class="nav nav-list">
  <li class="nav-header">Account Info</li>
  <li style="padding: 3px 0px">{{ request.user.email }}</li>
  <li style="padding: 3px 0px">Member since {{ request.user.date_joined|date:"Y M d" }}</li>
  <li>
  <a href="{% url password_change %}" class="nav-to-modal"
  data-form="{% url password_change %}">
  Change Password
  </a>
</ul>
{% endif %}
</div><!--/.well -->
</div><!-- span3 -->