www/aivs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template, redirect_to
from django.contrib import admin

from aivs import views

'''
This module performs the routing of URLs to the appropriate views and serves as the root
URL configuration file.  It routes by inclusion to the registration and admin URLs.
'''

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', direct_to_template, { 'template': 'home.html' }, name='home'),
    url(r'^home/$', redirect_to, { 'url': '/' }),
    url(r'^about/$', direct_to_template, { 'template': 'about.html' }, name='about'),
    url(r'^contact/$', views.contact, name='contact'),

    # these urls use the same view but control template with passed arguments
    url(r'^profile/$', views.profile_and_reports, { 'template': 'profile.html' }, name='profile'),
    url(r'^reports/$', views.profile_and_reports, { 'template': 'profile_table.html' }, name='reports'),

    # scan workflow urls
    url(r'^scan/$', views.request_scan, name='scan'),
    url(r'^scan_running/$', views.slideshow, name='slideshow'),
    url(r'^report/(?P<id>\d+)/$', views.scan_report, name='scan_report'),

    # included apps
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('registration_backend.urls')),  # registration must be before auth to override login
    url(r'', include('django.contrib.auth.urls')),
)

www/registration_backend/urls.py
from django.conf.urls import patterns, url
from django.views.generic.simple import direct_to_template
from django.contrib.auth import urls as auth_urls
from django.contrib.auth import views as auth_views

from registration.views import activate, register
import registration_backend
from registration_backend import forms

'''
The django-registration URL configuration has been reimplemented here so that we can override
the URLs, forms, and templates with ones of our choosing.

Registration workflow is:
register/       The user requests a scan and we take his name and email address.
registered/   After form validation, we tell the user to await an email from us.
activate/      The link the user clicks on from the email we send.
activated/    We have verified the user and queue the first scan.

Validation note from django-registration:
Activation keys get matched by \w+ instead of the more specific [a-fA-F0-9]{40} because a bad
activation key should still get to the view; that way it can return a sensible "invalid key" message
instead of a confusing 404.
'''

urlpatterns = patterns(
    '',
    url(r'^register/$',
        register,
        {'backend': 'registration_backend.AivsBackend',
         'success_url': 'registered/',
         'form_class': forms.RegistrationForm,
         'disallowed_url': 'closed/',
         'template_name': 'registration.html'},
        name='registration_register'),
    url(r'^register/registered/$',
        direct_to_template,
        {'template': 'registered.html'},
        name='registration_complete'),
    url(r'^activated/$',
        direct_to_template,
        {'template': 'activated.html'},
        name='registration_activation_complete'),
    url(r'^activate/(?P<activation_key>\w+)/$',
        activate,
        {'backend': 'registration_backend.AivsBackend'},
        name='registration_activate'),
    url(r'^closed/$',
        direct_to_template,
        {'template': 'closed.html'},
        name='registration_disallowed'),
    url(r'^login/$', auth_views.login, {'template_name':'registration/login.html',
                                        'authentication_form': forms.AivsAuthenticationForm}, name='auth_login'),
)

www/registration_backend/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from bootstrap.forms import BootstrapForm, Fieldset

class AivsAuthenticationForm(AuthenticationForm, BootstrapForm):
    '''
    A form to log the user in.
    '''
    class Meta:
        layout = (
            Fieldset("Log In",
                     'username',
                     'password'),
            )

    username = forms.EmailField( label = 'Email Address',
                                      initial = 'Enter your email address',
                                      widget = forms.Textarea(attrs = {'rows' : 1, 'class' : 'span3'}),
                                      help_text = 'Your valid email address, up to 200 characters.',
                                      error_messages = { 'required': 'You must supply your email address.',
                                                         'invalid': 'That does not appear to be a valid email address.',
                                                         'max_length': 'A maximum of 200 characters, please.'},
                                      max_length=200)

    password = forms.CharField(label = 'Password',
                               initial = 'Enter your password',
                               widget = forms.PasswordInput(attrs = {'rows' : 1, 'class' : 'span3'}),
                               help_text = 'Pick a strong password between 8 and 30 characters long.',
                               error_messages={'required': 'You must supply your password',
                                               'max_length':
                                               'Incorrect password.',
                                               'min_length':
                                               'Incorrect password.'},
                               min_length=8,
                               max_length=30)


class RegistrationForm(BootstrapForm):
    '''
    A form to initiate the registration workflow.
    '''
    class Meta:
        layout = (
            Fieldset("Register",
                     "first_name",
                     "last_name",
                     "email_address",
                     'password',
                     'password_verify',
                     "accepts_terms"),
            )

    first_name = forms.CharField( label = 'First Name',
                                  initial = 'Enter your first name',
                                  widget = forms.TextInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                  help_text = 'Your first name, up to 30 characters',
                                  error_messages = { 'required': 'You must supply your first name.',
                                                     'max_length': 'A maximum of 30 characters, please.'},
                                  max_length=30)

    last_name = forms.CharField( label = 'Last Name',
                                  initial = 'Enter your last name',
                                  widget = forms.TextInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                  help_text = 'Your last name, up to 30 characters',
                                  error_messages = { 'required': 'You must supply your last name.',
                                                     'max_length': 'A maximum of 30 characters, please.'},
                                  max_length=30)

    email_address = forms.EmailField( label = 'Email Address',
                                      initial = 'Enter your email address',
                                      widget = forms.TextInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                      help_text = 'Your valid email address, up to 200 characters.',
                                      error_messages = { 'required': 'You must supply an email address.',
                                                         'invalid': 'That does not appear to be a valid email address.',
                                                         'max_length': 'A maximum of 200 characters, please.'},
                                      max_length=200)

    password = forms.CharField(label = 'Password',
                               initial = 'Enter a password',
                               widget = forms.PasswordInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                               help_text = 'Pick a strong password between 8 and 30 characters long.',
                               error_messages={'required': 'You must choose a password',
                                               'max_length':
                                               'That is an awfully long password!  A max of 30 characters, please!',
                                               'min_length':
                                               'Choose a longer password.  A minimum of 8 characters, please.'},
                               min_length=8,
                               max_length=30)

    password_verify = forms.CharField(label = 'Verify Password',
                                      initial = 'Verify your password',
                                      widget = forms.PasswordInput(attrs = {'rows' : 1, 'class' : 'span4 input-large'}),
                                      help_text = 'Re-enter your password.',
                                      error_messages={'required': 'You must enter your password twice.'},
                                      max_length=30)

    accepts_terms = forms.BooleanField(
                                       error_messages={'required': 'You must accept the Terms and Conditions'})

    def clean_password(self):
        '''
        Verifies that the password matches the user-provided verfication and ensures it has appropriate
        complexity.
        '''
        candidate = self.data['password']
        if candidate != self.data['password_verify']:
            raise forms.ValidationError('Your passwords don\'t match.  Please try again.')

        # TODO: need complexity calculation here
        return self.data['password']

www/registration_backend/templates/activated.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block container %}
<h2>Account Activated!</h2>
<p>Your account activation has succeeded.  Redirecting you to the scanning page...</p>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$(document).ready(function() { setTimeout(window.location="{% url scan %}", 2000); })
</script>
{% endblock %}

www/registration_backend/templates/closed.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block container %}
<h2>Registration is Closed</h2>
<p>We're currently not taking any new users.  Please contact the site administrator if you would like to be notified as to when we might be back up and accepting new users.</p>
{% endblock %}

www/registration_backend/templates/register.html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML//EN">
<html> <head>
<title></title>
</head>

<body>
<form id="submit-form" action="/scan">
    {% csrf_token %}
    {{ form }}
</form>

$("#submit-form").live("submit", function(e) {
    e.preventDefault();
    $.ajax({
        type: "post",
        url: $("#submit-form").attr("action"),
        data: $("#submit-form").serialize(),
        dataType: "json",
        success: function(data) {
            if (data.error == 1) {
                $("#submit-form").replaceWith(data.message);
            } else {
                 //do something good
            }
        }
      }
    });
}



</body> </html>

www/registration_backend/templates/registered.html
{% extends "base.html" %}

{% block head %}{% endblock %}

{% block content %}
<h2>Initial Registration Complete!</h2>
<p>You're almost there! We've sent an email to the address you provided. Before we can start your scan, you need to click on the link in that email in order to authorize AIVScan. It also lets us authenticate your email address. Once you click on the link, you'll be directed back here.</p> 

<p>Be sure to check your Spam folder, too!</p>
{% endblock %}







 

www/registration_backend/templates/registration.html
{% extends "base_modal.html" %}
{% block modalform %}
<form id="modal-form" method="post" action="{% url registration_register %}" class="well form-vertical">

<div class="modal-header">
  <h2>Register</h2>
</div>

<div class="modal-body">
<p>Before using AIVScan, you first need to register. This helps us ensure that AIVScan is not being used for malicious purposes. It's super quick and relatively painless. Just fill out the form below and you'll be on your way to a safer, happier existence. Promise!</p>
<hr>

{% csrf_token %}
{{ form.non_field_errors }}
<div class="control-group">
  {{ form.first_name.errors }}
  <label for="id_first_name" class="regfields">First Name</label>
  <div class="controls">{{ form.first_name }}</div>
</div>
<div class="control-group">
  {{ form.last_name.errors }}
  <label for="id_last_name" class="regfields">Last Name</label>
  <div class="controls">{{ form.last_name }}</div>
</div>
<div class="control-group">
  {{ form.email_address.errors }}
  <label for="id_email_address" class="regfields">Email Address</label>
  <div class="controls">{{ form.email_address }}</div>
</div>
<div class="control-group">
  {{ form.password.errors }}
  <label for="id_password" class="regfields">Password</label>
  <div class="controls">{{ form.password }}</div>
</div>
<div class="control-group">
  {{ form.password_verify.errors }}
  <label for="id_password_verify" class="regfields">Confirm Password</label>
  <div class="controls">{{ form.password_verify }}</div>
</div>
<div class="control-group">
  {{ form.accepts_terms.errors }}
  <label class="checkbox">
  {{ form.accepts_terms }}
  <strong>I have read and accept AIVScan <a data-toggle="modal" href="#terms-modal">terms</a>.</strong>
  </label>
</div>
<div  class="form-actions">
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="#" class="btn" data-dismiss="modal">Cancel</a>
</div>
</form>
  <p class="help-block">NOTE: You will have the option to change profile settings later.</p>
</div> <!-- end modal body -->

<!-- terms and conditions modal -->
<div class="modal hide" id="terms-modal">
  <div class="modal-body">
{% include "terms_and_conditions.html" %}
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Close</a>
      </div>
 </div>
<!-- end terms and conditions modal -->

{% endblock %}